python scripts/generate_texture.py \
    --input_dir data/minivan/ \
    --output_dir outputs/minivan \
    --obj_name mesh \
    --obj_file mesh.obj \
    --prompt "a blue minivan" \
    --add_view_to_prompt \
    --ddim_steps 30 \
    --new_strength 1.0 \
    --update_strength 0.3 \
    --view_threshold 0.4 \
    --blend 0 \
    --dist 1 \
    --num_viewpoints 36 \
    --viewpoint_mode predefined \
    --use_principle \
    --update_steps 30 \
    --update_mode heuristic \
    --seed 42 \
    --post_process \
    --device "2080" \
    --resampling 3  \
    --training      \
    --use_patch     \
    --flexible_view   \
    --use_objaverse  \
    --num_images 3   
    # assume the mesh is normalized with y-axis as up
